config/routes.rb
Rails.application.routes.draw do

  get "admin/index"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  resources :users
  resources :sessions
  resources :players do
    resources :seasons
  end
  resources :seasons do
    get :edit_players, :on => :member
    get :generate_schedule, :on => :member
    post :update_players, :on => :member
    post :run_generate_schedule, :on => :member
    resources :players
    resources :games do
      get :seat_players, :on => :member
      get :select_place, :on => :member
      get :set_subs, :on => :member
      post :update_seating, :on => :member
      post :update_place, :on => :member
      post :update_subs, :on => :member
      resources :tables
    end     
  end
  
  if ENV['RAILS_ENV'] == 'production'
    root :to => 'seasons#show', :id => '3'
  else
    root :to => 'seasons#index' 
  end

end

app/models/season.rb
class Season < ActiveRecord::Base  
  has_and_belongs_to_many :players
  has_many :games, :dependent => :destroy
  has_many :tables, :through => :games

  validates :number_of_games, :numericality => { :only_integer => true }
  validates :number_of_tables, :numericality => { :only_integer => true }
  validates :name, :presence => true

  def generate_schedule
    if !self.locked    
      (1..self.number_of_games).each do |game|
        current_game = Game.new(:number => game)
        (1..self.number_of_tables).each do |table|
          current_table = Table.new(:number => table)
          current_game.tables << current_table
        end
        self.games << current_game
      end
      self.locked = true
      self.save
    end
  end

  def games_played
    @games_played = 0
    self.games.order("number").each do |game|
      if game.finished? 
        @games_played += 1
      else
        break
      end
    end
    @games_played
  end 

  def games_to_display   
    @games_played = 0
    self.games.order("number").each do |game|
      if game.finished? || game.in_progress?
        @games_played += 1
      else
        break
      end
    end
    @games_played
  end

  
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  layout :pick_layout

  # before_filter :require_login

  # GET /seasons
  # GET /seasons.json
  def index
    @seasons = Season.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @seasons }
    end
  end

  def show
    @season = Season.find(params[:id])
    @players = @season.players
    @all_players = Player.all
    @subs = @all_players - @players
    @players_total_points = {}

    @games = @season.games.order(:number)
    @games_to_display = @games[0..(@season.games_to_display - 1)]

    @players = @players.sort { |x, y| x.total_points(@season)[0] <=> y.total_points(@season)[0] }  
    @players = @players.reverse  

    if !current_user
      render 'season_results'
    end
  end

  # GET /seasons/new
  # GET /seasons/new.json
  def new
    @season = Season.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @season }
    end
  end

  # GET /seasons/1/edit
  def edit
    @season = Season.find(params[:id])
  end

  # POST /seasons
  # POST /seasons.json
  def create
    @season = Season.new(season_params)

    respond_to do |format|
      if @season.save
        format.html { redirect_to @season, notice: 'Season was successfully created.' }
        format.json { render json: @season, status: :created, location: @season }
      else
        format.html { render action: "new" }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @season = Season.find(params[:id])
    updates = season_update_params
    if @season.locked
      updates.delete("number_of_games")
      updates.delete("number_of_tables")
    end
    if @season.update_attributes(updates)
      redirect_to @season, notice: 'Season was successfully updated.'        
    else
      render action: "edit_details" 
    end
  end

  # DELETE /seasons/1
  # DELETE /seasons/1.json
  def destroy
    @season = Season.find(params[:id])
    @season.destroy

    respond_to do |format|
      format.html { redirect_to seasons_url }
      format.json { head :ok }
    end
  end

  def edit_players
    @season = Season.find(params[:id])
    @players_in_this_season = @season.players 
    @players = Player.order('name')
  end

  def update_players
    @players = Player.all
    @season = Season.find(params[:id])
    @players.each do |player|
      if params[player.id.to_s] == "1"
        player.add_to_season(@season)
      else
        player.remove_from_season(@season)
      end
    end
    redirect_to @season
  end

  def generate_schedule
    @season = Season.find(params[:id])
    @players = @season.players
  end

  def run_generate_schedule
    @season = Season.find(params[:id])
    @season.generate_schedule
    redirect_to @season
  end

  private

  def season_params
    params.require(:season).permit(:name)
  end     

  def season_update_params
    params.require(:season).permit(:name, :number_of_games, :number_of_tables, :notes, :visible)
  end
end

app/views/seasons/_form.html.erb
<%= form_for(@season) do |f| %>
  <% if @season.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@season.errors.count, "error") %> prohibited this season from being saved:</h2>

      <ul>
      <% @season.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seasons/edit.html.erb
<% if @season.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@season.errors.count, "error") %> prohibited this season from being saved:</h2>

    <ul>
    <% @season.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_for @season do |f| %>
  <table>
    <tr>
      <td><%= f.label :name %></td>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <td><%= f.label :number_of_games %></td>
      <td><%= f.text_field :number_of_games %></td>
    </tr>
    <tr>
      <td><%= f.label :number_of_tables %></td>
      <td><%= f.text_field :number_of_tables %></td>
    </tr>
    <tr>
      <td><%= f.label :notes %></td>
      <td><%= f.text_area :notes, :size => "60x12" %></td>
    </tr>
    <tr>
      <td><%= f.label :visible_to_public %></td>
      <td><%= f.check_box :visible %></td>
    </tr>
  </table>  
  <%= f.submit "Update" %>
<% end %>

app/views/seasons/edit_players.html.erb
Season name: <%= @season.name %>
<br>
<br>
Add Players to this season:<br>
<br>
<%= form_tag update_players_season_path(@season) do %>
  <table>
    <tr>
      <td>
        Name
      </td>
      <td>
        In This Season
      </td>
      <td>
        Sub
      </td>
    </tr>
    <% @players.each do |player| %>
      <tr>
        <td>
          <%= player.name %>
        </td>
        <td>
          <%= 
            if player.is_in_season?(@season)            
              radio_button_tag(player.id, "1", :checked => true)
            else
              radio_button_tag(player.id, "1") 
            end
          %>
        </td>
        <td>
          <%= 
            if player.is_in_season?(@season)            
              radio_button_tag(player.id, "0")
            else
              radio_button_tag(player.id, "0", :checked => true) 
            end
          %>
        </td>
      </tr>        
    <% end %>
  </table>
  <%= submit_tag("Update Players") %>  
<% end %>

<br>
<br>
List of players:<br>
<br>
<ul>
  <% @players_in_this_season.each do |player| %>
    <li>
      <%= player.name %>
    </li>
  <% end %>
</ul>
<br>
<br>
List of all Players:<br>
<br>
<ul>
  <% @players.each do |player| %>
    <li>
      <%= player.name %>
    </li>
  <% end %>
</ul>

app/views/seasons/generate_schedule.html.erb
<h3>Generate Schedule</h3>
<p>
This will lock the players, number of games, and number of tables and generate the schedule
for the season. Ensure that the following is correct before hitting the "Generate" button.
</p>

<h4>Number of games:</h4>
<p><%= @season.number_of_games %>

<h4>Number of tables:</h4>
<p><%= @season.number_of_tables %>

<h4>Number of players:</h4>
<p><%= @players.size %></p>

<h4>Player list</h4>
<ul>
  <% @players.each do |player| %>
    <li><%= player.name %></li>
  <% end %>
</ul>

<%= form_tag run_generate_schedule_season_path(@season) do %>
  <%= submit_tag("Generate") %>  
<% end %>

app/views/seasons/index.html.erb
<h1>Seasons</h2>

<ul>
  <% @seasons.each do |season| %>
    <% if season.visible == true || current_user %>
      <li><%= link_to season.name, season %></li>
    <% end %>
  <% end %>
</ul>

<br />

<% if current_user %>
  <%= link_to 'New Season', new_season_path %>
<% end %>

app/views/seasons/new.html.erb
<h1>New season</h1>

<%= render 'form' %>

<%= link_to 'Back', seasons_path %>

app/views/seasons/season_results.html.erb
<% content_for :navigation do %>
  <%= link_to "Back", seasons_path %>
<% end %>

<table>
  <thead>
    <tr>
      <th></td>
      <th></th>   
      <% @games_to_display.each_with_index do |game, index| %>
        <% if index == 0 %>
          <th id="left-border">
        <% else %>        
          <th class="game">
        <% end %>
        <%= link_to "Game #{game.number}", season_game_path(@season, game) %></th>
      <% end %>
      <th id="right-border">Total Points</th>  
    </tr>
  </thead>
  <% @last_points = 1000 %>
  <% @last_place %>
  <% @players.each_with_index do |player, index| %>
    <tr class="<%= cycle("even", "odd") %>">
      <% if index == 0 %>      
        <td id="top-left">
      <% elsif index == 15 %>
        <td id="bottom-left">
      <% else %>
        <td>
      <% end %>
        <!-- TODO This is garbage, but was interesting problem to hack this way (tired) -->
        <% if player.total_points(@season)[0] < @last_points %>
          <% @last_place = index + 1 %>
          <% @last_points = player.total_points(@season)[0] %>
          <%= (index + 1).ordinalize %>
        <% else %>
          <%= @last_place.ordinalize %>
        <% end %>
      </td>
      <td><%= link_to player.name, season_player_path(@season, player.id) %></td>
      <% @games_to_display.each do |game| %>
        <td><%= player.points_in_game(game) %></td>
      <% end %>
      <% if index == 15 %>
        <td id="bottom-right">
      <% else %>
        <td>
      <% end %>
        <%= player.total_points(@season)[0] %>
        <% if player.total_points(@season)[1] != 0 %>
          (<%= player.total_points(@season)[0] + player.total_points(@season)[1] %>)
        <% end %>
      </td>
    <tr>       
  <% end %>
</table>

app/views/seasons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <% if @season.locked %>
    Season is locked
  <% else %>
    <%= link_to "Generate Season", generate_schedule_season_path(@season) %>
  <% end %>
</p>

<% if @season.locked %>
  <p><%= link_to "Show Games", season_games_path(@season) %></p>
<% else %>
  <p><%= link_to 'Delete Season', @season, confirm: 'Are you sure?', method: :delete %></p> 
<% end %>

<p>
  <b>Details:</b> <%= link_to "Edit Details", edit_season_path(@season) %> <br>
  Name: <%= @season.name %><br>
  Number Of Games: <%= @season.number_of_games %><br>
  Number Of Tables: <%= @season.number_of_tables %><br>
  Notes: <%= @season.notes %><br>
</p>

<p>
  <b>Players:</b> (<%= @players.size %>)
  <% if !@season.locked %>    
    <%= link_to "Edit Players", edit_players_season_path(@season) %>
  <% end %>
  <ul>
    <% @players.each do |player|%>
      <li><%= player.name %></li>
    <% end %>
  </ul>
</p>