config/routes.rb
Rails.application.routes.draw do

  get "admin/index"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  resources :users
  resources :sessions
  resources :players do
    resources :seasons
  end
  resources :seasons do
    get :edit_players, :on => :member
    get :generate_schedule, :on => :member
    post :update_players, :on => :member
    post :run_generate_schedule, :on => :member
    resources :players
    resources :games do
      get :seat_players, :on => :member
      get :select_place, :on => :member
      get :set_subs, :on => :member
      post :update_seating, :on => :member
      post :update_place, :on => :member
      post :update_subs, :on => :member
      resources :tables
    end     
  end
  
  if ENV['RAILS_ENV'] == 'production'
    root :to => 'seasons#show', :id => '3'
  else
    root :to => 'seasons#index' 
  end

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :season
  has_many :tables, :dependent => :destroy
  has_many :seats, :through => :tables 

  def previous_game_concluded?(game)
    @season = game.season    
    @result = true
    if game.number != 1
      @previous_game = @season.games.where(:number => (game.number - 1)).first
      @previous_tables = @previous_game.tables
      @result = true
      @previous_tables.each do |table|
        if table.players_still_playing.size != 0 || table.seats.size == 0
          @result = false
        end
      end
    end
    @result
  end
  
  def current_game_not_started?(game)
    @tables = game.tables
    @result = true
    @tables.each do |table|
      if table.players_finished.size != 0
        @result = false
      end
    end
    @result
  end
  
  def can_seat_players?
    #seat players option is available if the last game is concluded and 
    #this game hasn't started yet
    current_game_not_started?(self) && previous_game_concluded?(self)   
  end

  def finished?
    @result = true
    self.tables.each do |table|
      if table.players_still_playing.size != 0 || table.seats.size == 0
        @result = false
      end
    end
    @result
  end

  def in_progress?
    @result = false
    self.tables.each do |table|
      if table.players_still_playing.size != 0
        @result = true
      end
    end
    @result  
  end
        
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  layout :pick_layout
  before_filter :require_login, :except => :show


  def index
    @season = Season.find(params[:season_id])
    @games = @season.games.order('number')
  end


  def show
    @game = Game.find(params[:id])
    @season = Season.find(params[:season_id])
    @players = Player.all
    @name_lookup = Hash.new
    @players.each do |player|
      @name_lookup[player.id] = player.name
    end
  end

  def set_subs
    @season = Season.find(params[:season_id])
    @game = Game.find(params[:id])
    @tables = @game.tables
    @season_players = @season.players
    @all_players = Player.all
    @subs = @all_players - @season_players
    @subs_list = [["No Sub", 0]] + @subs.map { |player| [player.name, player.id] }
  end

  def update_subs
    @seat = Seat.find(params[:seat_id])
    if params[:player_id] == "0"
      @seat.update_attributes(:sub_id => nil)
    else
      @seat.update_attributes(:sub_id => params[:player_id])
    end
    redirect_to set_subs_season_game_path(params[:season_id], params[:id])
  end

  def edit
    
  end

  def seat_players
    @season = Season.find(params[:season_id])
    @game = Game.find(params[:id])
    @tables = @game.tables
    @players = @season.players.order("name")
  end

  def update_seating
    @season = Season.find(params[:season_id])
    @game = Game.find(params[:id])
    @players = @season.players
    
    if @game.seats.size > 0 
      @game.seats.each do |seat|
        seat.update_attributes(:table_id => params[seat.player_id.to_s])
      end
    else
      @players.each do |player|
        #player is the hash key for the table number
        Seat.create(:player_id => player.id, :table_id => params[player.id.to_s])
      end
    end
    redirect_to season_games_path(@season) 
  end  

  def select_place
    @season = Season.find(params[:season_id])
    @game = Game.find(params[:id])
    @tables = @game.tables
        
    @games = @season.games.order(:number)
    @games_to_display = @games[0..(@season.games_to_display - 1)]
    @players = @season.players
    @players = @players.sort { |x, y| x.total_points(@season)[0] <=> y.total_points(@season)[0] }  
    @players = @players.reverse  
    
  end

  def update_place
    @season = Season.find(params[:season_id])
    @game = Game.find(params[:id])
    @table = Table.find(params[:table_id])

    if params[:undo] == '1'
      if @table.players_still_playing.size == 0
        @seat = Seat.where(:table_id => params[:table_id]).order(:place).first
        @seat.update_attributes(:place => nil)
      end
      @seat = Seat.where(:table_id => params[:table_id]).order(:place).first
      @seat.update_attributes(:place => nil)
    else
      @seat = Seat.where(:player_id => params[:player_id], :table_id => params[:table_id]).first
      @place = @table.players.size - @table.players_finished.size
      @seat.update_attributes(:place => @place)
      @players_left = @table.players_still_playing
      if @players_left.size == 1 
        @first_place = @players_left.first
        @seat = Seat.where(:player_id => @first_place.id, :table_id => params[:table_id]).first
        @seat.update_attributes(:place => 1)
      end

    end 

    redirect_to select_place_season_game_path(@season, @game)

  end


  def update
    
    @game = Game.find(params[:id])
    @game.update_attributes(game_update_params)
    redirect_to season_games_path(@game.season) 

  end

  private

  def game_update_params
    params.require(:game).permit(:date)
  end  

end

app/views/games/index.html.erb
<% content_for :navigation do %>
  <%= link_to "Back", season_path(@season) %>
<% end %>

<h4>Games:</h4>
<table class="admin">
  <tr>
    <td>Game</td>
    <td>Date</td>
    <td>Seat Players</td>
    <td>Select Place</td>
    <td>Set Subs</td>
    <td>Change Date</td>
  </tr>
  <% @games.each do |game| %>
    <tr>
      <td><%= game.number %></td>
      <td>
        <% if !game.date.nil? %>
          <%= game.date.strftime("%B %e, %Y") %></td>
        <% end %>
      <td>
        <% if game.can_seat_players? %>
          <%= link_to "Seat Players", seat_players_season_game_path(@season, game) %>
        <% end %>
      </td>
      <td>
        <% if game.in_progress? || game.finished? %>
          <%= link_to "Select Place", select_place_season_game_path(@season, game) %>
        <% end %>
      </td>
      <td>
        <% if game.in_progress? || game.finished? %>
          <%= link_to "Set subs", set_subs_season_game_path(@season, game) %>
        <% end %>
      </td>
      <td>
        <%= form_tag(season_game_path(@season, game), :method => "put") do %>
          <%= date_select :game, :date, :default => game.date, 
                                        :order => [:month, :day, :year] %>
                                        
          <%= submit_tag "Update" %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/games/seat_players.html.erb
<% content_for :navigation do %>
  <%= link_to "Back", season_games_path(@season) %>
<% end %> 

<h4> Season: <%= @season.name %></h4>
<h4>Game: Game #<%= @game.number %></h4>

<%= form_tag update_seating_season_game_path(@season, @game) do %>
  <table class="admin">
    <tr>
      <td>
        Player
      </td>
      <% @tables.each do |table| %>
        <td>
          Table #<%= table.number %>
        </td>
      <% end %>
    </tr>
    <% @players.each do |player| %>
      <tr>
        <td>
          <%= player.name %>
        </td>
        <% @tables.each do |table| %>
          <td>
            <% if player.is_at_table?(table) %>
              <%= radio_button_tag(player.id, table.id, :checked => true) %>
            <% else %>
              <%= radio_button_tag(player.id, table.id) %>
            <% end %>
          </td>
        <% end %>
      </tr>        
    <% end %>
  </table>
  <%= submit_tag("Seat Players") %>  
<% end %>

app/views/games/select_place.html.erb
<% content_for :navigation do %>
  <%= link_to "Back", season_games_path(@season) %>
<% end %>


<% @tables.each do |table| %>
  <h4>Table #<%= table.number %></h4>
  <table class="admin">
    <tr>
      <td>Players still playing:</td>
      <td>Finished:</td>
      <td>Select Next Place:</td>
    </tr>
    <tr>
      <td>
        <ul>
          <% table.players_still_playing.each do |player| %>
            <li><%= player.name %></li>
          <% end %>
        </ul>
      </td>
      <td>
        <ul>
          <% table.players_finished.each do |player| %>
            <li><%= player.seats.where(:table_id => table.id).first.place.ordinalize %> - <%= player.name %>
          <% end %>
        </ul>
      </td>
      <td>
        <% if table.players_still_playing.size != 0 %>
          Select <%= (table.players.size - table.players_finished.size).ordinalize %> place.<br>       
          <%= form_tag update_place_season_game_path(@season, @game) do %>
            <%= select_tag(:player_id, 
              options_for_select(table.players_still_playing.map { |player| [player.name, player.id] } )) %>
            <%= hidden_field_tag(:table_id, table.id) %>
            <%= submit_tag("Submit") %>
          <% end %><br>
        <% end %>
        <% if table.players_finished.size != 0 %>
          <%= form_tag update_place_season_game_path(@season, @game) do %>
            <%= hidden_field_tag(:table_id, table.id) %>
            <%= hidden_field_tag(:undo, 1) %>
            <%= submit_tag("Undo") %>
          <% end %>
        <% end %>
      </td>
    </tr>
  </table>
<% end %> 

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>   
      <% @games_to_display.each_with_index do |game, index| %>
        <% if index == 0 %>
          <th id="left-border">
        <% else %>        
          <th class="game">
        <% end %>
        <%= link_to "Game #{game.number}", season_game_path(@season, game) %></th>
      <% end %>
      <th id="right-border">Total Points</th>  
    </tr>
  </thead>
  <% @last_points = 1000 %>
  <% @last_place %>
  <% @players.each_with_index do |player, index| %>
    <tr class="<%= cycle("even", "odd") %>">
      <% if index == 0 %>      
        <td id="top-left">
      <% elsif index == 15 %>
        <td id="bottom-left">
      <% else %>
        <td>
      <% end %>
        <!-- TODO This is garbage, but was interesting problem to hack this way (tired) -->
        <% if player.total_points(@season)[0] < @last_points %>
          <% @last_place = index + 1 %>
          <% @last_points = player.total_points(@season)[0] %>
          <%= (index + 1).ordinalize %>
        <% else %>
          <%= @last_place.ordinalize %>
        <% end %>
      </td>
      <td><%= link_to player.name, season_player_path(@season, player.id) %></td>
      <% @games_to_display.each do |game| %>
        <td><%= player.points_in_game(game) %></td>
      <% end %>
      <% if index == 15 %>
        <td id="bottom-right">
      <% else %>
        <td>
      <% end %>
        <%= player.total_points(@season)[0] %>
        <% if player.total_points(@season)[1] != 0 %>
          (<%= player.total_points(@season)[0] + player.total_points(@season)[1] %>)
        <% end %>
      </td>
    <tr>       
  <% end %>
</table>

app/views/games/set_subs.html.erb
<% content_for :navigation do %>
  <%= link_to "Back", season_games_path(@season) %>
<% end %>

<h2>Game #<%= @game.number %></h2>

<% @tables.each do |table| %>
  <h4>Table #<%= table.number %></h4>
  <table class="admin">
    <tr>
      <td width=100>Player</td>
      <td width=100>Sub</td>
      <td>Update Sub</td>
    </tr>
    <% table.seats.order("id").each do |seat| %>
      <tr>
        <td><%= seat.player.name %></td>
        <td><%= seat.sub_name %></td>
        <td>
          <%= form_tag update_subs_season_game_path(@season, @game) do %>
            <%= select_tag(:player_id, 
              options_for_select(@subs_list)) %>
            <%= hidden_field_tag(:seat_id, seat.id) %>
            <%= submit_tag("Update") %>
          <% end %>
        </td>
      <tr>
    <% end %>
  </table>
<% end %>

app/views/games/show.html.erb
<% content_for :navigation do %>
  <%= link_to "Back", season_path(@season) %>
<% end %>

<h2>Game #<%= @game.number %> - <%= @game.date.strftime("%B %e, %Y") %></h2> 

<% @game.tables.each do |table| %>
  <table class="single-game">
    <caption>Table <%= table.number %></caption>
    <% table.seats_in_order_of_place.each_with_index do |seat, index| %>
      <tr class="<%= cycle("odd", "even")%>">
        <% if index == 0 %>
          <td id="top-left">
        <% elsif index == 7 %>
          <td id="bottom-left">
        <% else %>
          <td>
        <% end %>
          <%= seat.place.ordinalize if seat.place %>
        </td>
        <% if index == 0 %>
          <td id="top-right">
        <% elsif index == 7 %>
          <td id="bottom-right">
        <% else %>
          <td>
        <% end %>
          <%= link_to seat.player.name, season_player_path(@season, seat.player) %>
          <% if seat.sub_id != nil %>
            (<%= @name_lookup[seat.sub_id] %>)
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>  
<% end %>