config/routes.rb
Rails.application.routes.draw do

  get "admin/index"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  resources :users
  resources :sessions
  resources :players do
    resources :seasons
  end
  resources :seasons do
    get :edit_players, :on => :member
    get :generate_schedule, :on => :member
    post :update_players, :on => :member
    post :run_generate_schedule, :on => :member
    resources :players
    resources :games do
      get :seat_players, :on => :member
      get :select_place, :on => :member
      get :set_subs, :on => :member
      post :update_seating, :on => :member
      post :update_place, :on => :member
      post :update_subs, :on => :member
      resources :tables
    end     
  end
  
  if ENV['RAILS_ENV'] == 'production'
    root :to => 'seasons#show', :id => '3'
  else
    root :to => 'seasons#index' 
  end

end

app/models/player.rb
class Player < ActiveRecord::Base
  has_and_belongs_to_many :seasons
  has_many :seats
  has_many :tables, :through => :seats

  def is_in_season?(season)
    self.seasons.include?(season)
  end

  def add_to_season(season)
    if self.is_in_season?(season) == false
      self.seasons << season
    end
  end

  def remove_from_season(season)
    if self.is_in_season?(season)
      self.seasons.delete(season)
    end
  end

  def is_at_table?(table)
    seat = Seat.where(:player_id => self.id, :table_id => table.id)
    seat.size == 1
  end

  #TODO should be for one season
  def total_points(season)
    @total = []
    @total[0] = 0 
    @total[1] = 0  
    self.seats_in_season(season).each do |seat|
      if seat.table.game.in_progress?      
        if seat.place 
          @total[1] += (9 - seat.place)
        end
      else
        if seat.place
          @total[0] += (9 - seat.place)
        end
      end
    end
    @total  
  end  

  def points_in_game(game)
    seat = game.seats.where(:player_id => self.id).first
    @return    
    if seat
      if seat.place
        @return = 9 - seat.place
      else
        @return = ""
      end
    else
      @return = ""
    end
    @return
  end  

  def tables_to_display(season)
    Table.find_by_sql("SELECT tables.id, tables.game_id, tables.number FROM players, seats, tables, games, seasons WHERE
      seats.player_id = players.id AND seats.table_id = tables.id AND 
      tables.game_id = games.id AND games.season_id = seasons.id AND    
      players.id = #{self.id} AND seasons.id = #{season.id}
      ORDER BY games.number ASC;")
  end

  def seats_in_season(season)
    Seat.find_by_sql(" SELECT seats.place, seats.id, seats.player_id, seats.table_id 
      FROM seats, players, tables, games, seasons WHERE 
      seats.player_id = players.id AND tables.id = seats.table_id AND
      tables.game_id = games.id AND games.season_id = seasons.id AND
      players.id = #{self.id} AND seasons.id = #{season.id}")
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController 
  layout :pick_layout
  
  # before_filter :require_login


  # GET /players
  # GET /players.json
  def index
    @players = Player.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players }
    end
  end

  def show
    @player = Player.find(params[:id])
    if params[:season_id]
      @season = Season.find(params[:season_id])
      @games = @season.games.order(:number)
      @games_to_display = @games[0..(@season.games_to_display - 1)]
      @tables_to_display = @player.tables_to_display(@season)
      @players = Player.all      
      @name_lookup = Hash.new
      @players.each do |player|
        @name_lookup[player.id] = player.name
      end
      render :season_results      
    end
  end

  # GET /players/new
  # GET /players/new.json
  def new
    @player = Player.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/1/edit
  def edit
    @player = Player.find(params[:id])
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render json: @player, status: :created, location: @player }
      else
        format.html { render action: "new" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /players/1
  # PUT /players/1.json
  def update
    @player = Player.find(params[:id])

    respond_to do |format|
      if @player.update_attributes(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :ok }
    end
  end

  private

  def player_params
    params.require(:player).permit(:email, :name)
  end


end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<h1>Listing players</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @players.each do |player| %>
  <tr>
    <td><%= player.name %></td>
    <td><%= player.email %></td>
    <td><%= link_to 'Show', player %></td>
    <td><%= link_to 'Edit', edit_player_path(player) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/season_results.html.erb
<% content_for :navigation do %>
  <%= link_to "Back", season_path(@season) %>
<% end %>

<h2><%= @player.name %></h2>

<% @tables_to_display.each do |table| %>
  <table class="single-game">
    <caption><%= link_to "Game #{table.game.number}", season_game_path(@season, table.game) %></caption>
    <% table.seats_in_order_of_place.each_with_index do |seat, index| %>      
      <tr class="<%= cycle("odd", "even")%>">
        <% if index == 0 %>
          <td id="top-left">
        <% elsif index == 7 %>
          <td id="bottom-left">
        <% else %>
          <td>
        <% end %>
          <p <%= "class=emphasize" if seat.player_id == @player.id %>>
          <%= seat.place.ordinalize if seat.place %>
        </td>
        <% if index == 0 %>
          <td id="top-right">
        <% elsif index == 7 %>
          <td id="bottom-right">
        <% else %>
          <td>
        <% end %>
          <%= link_to seat.player.name, season_player_path(@season, seat.player) %>
          <% if seat.sub_id != nil %>
            (<%= @name_lookup[seat.sub_id] %>)
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>  
<% end %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @player.name %>
</p>

<p>
  <b>Email:</b>
  <%= @player.email %>
</p>


<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>