config/routes.rb
Rails.application.routes.draw do

  get "admin/index"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  resources :users
  resources :sessions
  resources :players do
    resources :seasons
  end
  resources :seasons do
    get :edit_players, :on => :member
    get :generate_schedule, :on => :member
    post :update_players, :on => :member
    post :run_generate_schedule, :on => :member
    resources :players
    resources :games do
      get :seat_players, :on => :member
      get :select_place, :on => :member
      get :set_subs, :on => :member
      post :update_seating, :on => :member
      post :update_place, :on => :member
      post :update_subs, :on => :member
      resources :tables
    end     
  end
  
  if ENV['RAILS_ENV'] == 'production'
    root :to => 'seasons#show', :id => '3'
  else
    root :to => 'seasons#index' 
  end

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PkrBk</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="container">
  <div id="banner">
    <% if current_user %>
      Logged in as <%= current_user.username %>.
      <%= link_to "Log out", logout_path %>
    <% end %>
  </div>
  <div id="navigation">
    <div id="left-navigation"><%= yield :navigation %></div>
    <div id="right-navigation">
      <%= link_to "Players", players_path %>
      <%= link_to "Seasons", seasons_path %>
    </div>    
  </div> 
  <div id="content"><%= yield %></div>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PkrBk</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
  Logged in as <%= current_user.username %>. <%= link_to "Log out", logout_path %>
<% end %>

<div id="container">
  <div id="banner"></div>
  <div id="navigation"><%= yield :navigation %></div> 
  <div id="content"><%= yield %></div>
</div>

</body>
</html>